### ISSUE TITLE
Cursor jumps to the old length of the selection after evaluation

### ISSUE THREAD

**Issue by jafd** [jbrooksuk/Sublime-Evaluate#5]
Here's the problem:

1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1

it evaluates to 9, which is 1 character long, but the cursor jumps 33 characters to the right. This disturbs the flow: you meant to insert some text right after the sum, and ended up damaging the next paragraph.

**Comment by jbrooksuk** [comment]
👍  I'll fix this.

**Comment by jbrooksuk** [comment]
Fixed!
